In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
movies = pd.read_csv(r"F:\Ritesh\IMDB_Movies.csv")
orgdata = movies

In [8]:
movies.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [9]:
###Cleaning the data###
#Columnwise null count##
movies.isnull().sum(axis=0).sort_values(ascending=False)

gross                        884
budget                       492
aspect_ratio                 329
content_rating               303
plot_keywords                153
title_year                   108
director_name                104
director_facebook_likes      104
num_critic_for_reviews        50
actor_3_name                  23
actor_3_facebook_likes        23
num_user_for_reviews          20
color                         19
duration                      15
language                      14
facenumber_in_poster          13
actor_2_name                  13
actor_2_facebook_likes        13
actor_1_name                   7
actor_1_facebook_likes         7
country                        5
cast_total_facebook_likes      0
num_voted_users                0
movie_title                    0
movie_imdb_link                0
genres                         0
imdb_score                     0
movie_facebook_likes           0
dtype: int64

In [10]:
#Row wise null count#
movies.isnull().sum(axis=1).sort_values(ascending=False)

279     15
4       13
2241    11
4945    11
2342    10
        ..
1703     0
1702     0
1701     0
1700     0
5042     0
Length: 5043, dtype: int64

In [11]:
#For columnwise null percentages#
movies.isnull().sum(axis=0).sort_values(ascending=False)/len(movies
) * 100

gross                        17.529248
budget                        9.756098
aspect_ratio                  6.523895
content_rating                6.008328
plot_keywords                 3.033908
title_year                    2.141582
director_name                 2.062265
director_facebook_likes       2.062265
num_critic_for_reviews        0.991473
actor_3_name                  0.456078
actor_3_facebook_likes        0.456078
num_user_for_reviews          0.396589
color                         0.376760
duration                      0.297442
language                      0.277613
facenumber_in_poster          0.257783
actor_2_name                  0.257783
actor_2_facebook_likes        0.257783
actor_1_name                  0.138806
actor_1_facebook_likes        0.138806
country                       0.099147
cast_total_facebook_likes     0.000000
num_voted_users               0.000000
movie_title                   0.000000
movie_imdb_link               0.000000
genres                        0.000000
imdb_score                    0.000000
movie_facebook_likes          0.000000
dtype: float64

In [12]:
#Dropping unwanted columns#
movies = movies.drop(['color','director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes',
'actor_3_facebook_likes','actor_2_name','cast_total_facebook_likes','actor_3_name','duration','facenumber_in_poster','content_rating','country','movie_imdb_link',
'aspect_ratio','plot_keywords'], axis=1)

In [13]:
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force AwakensÂ ...,8,,NaN,NaN,NaN,7.1,0

In [14]:
#Dropping the rows#
round(movies.isnull().sum(axis=0).sort_values(ascending=False)/len(
movies)*100,2)

gross                     17.53
budget                     9.76
title_year                 2.14
director_name              2.06
num_critic_for_reviews     0.99
num_user_for_reviews       0.40
language                   0.28
actor_1_name               0.14
genres                     0.00
movie_title                0.00
num_voted_users            0.00
imdb_score                 0.00
movie_facebook_likes       0.00
dtype: float64

In [15]:
movies=movies[movies['gross'].notnull()]
movies=movies[movies['budget'].notnull()]
round(movies.isnull().sum().sort_values(ascending=False)/len(movies)*100,2)

language                  0.10
actor_1_name              0.08
num_critic_for_reviews    0.03
director_name             0.00
gross                     0.00
genres                    0.00
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

In [16]:
#Dropping the rows#
(movies.isnull().sum(axis=1).sort_values(ascending=False)>5).sum()
movies=movies[movies.isnull().sum(axis=1).sort_values(ascending=False)<=5]

C:\Users\hp\AppData\Local\Temp\ipykernel_11712\2497623194.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  movies=movies[movies.isnull().sum(axis=1).sort_values(ascending=False)<=5]

In [17]:
#Filing the missing nan values#
round(movies.isnull().sum().sort_values(ascending=False)/len(movies)*100,2)

language                  0.10
actor_1_name              0.08
num_critic_for_reviews    0.03
director_name             0.00
gross                     0.00
genres                    0.00
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

In [18]:
#We can see that the Language column has some NaN values, we will replace that with English since its in the Max#
movies.groupby('language').language.count().sort_values(ascending=False)

language
English       3707
French          37
Spanish         26
Mandarin        15
German          13
Japanese        12
Hindi           10
Cantonese        8
Italian          7
Korean           5
Portuguese       5
Norwegian        4
Dutch            3
Persian          3
Hebrew           3
Danish           3
Thai             3
Aboriginal       2
Indonesian       2
Dari             2
Arabic           1
Romanian         1
Vietnamese       1
Aramaic          1
Telugu           1
Swedish          1
Bosnian          1
Russian          1
Czech            1
Icelandic        1
Dzongkha         1
Mongolian        1
Maya             1
Filipino         1
Hungarian        1
Kazakh           1
Zulu             1
Name: language, dtype: int64

In [19]:
movies.language = movies.language.fillna('English')

In [20]:
###MOVIES WITH HIGHEST PROFIT###
#changing the unit of the budget and gross columns from $ to million $#
movies['budget']=movies['budget']/1000000
movies['gross']=movies['gross']/1000000

In [21]:
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,300.0,2007.0,7.1,0
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,245.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,250.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738,English,263.7,2012.0,6.6,24000

In [22]:
#creating new column name profit#
movies['profit']=movies['gross']-movies['budget']

In [23]:
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237.0,2009.0,7.9,33000,523.505847
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238,English,300.0,2007.0,7.1,0,9.404152
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994,English,245.0,2015.0,6.8,85000,-44.925825
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701,English,250.0,2012.0,8.5,164000,198.130642
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738,English,263.7,2012.0,6.6,24000,-190.641321

In [24]:
#sorting everything in descending order#
movies.sort_values(by='profit',ascending=False)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237.000000,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290,English,150.000000,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528,English,200.000000,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470,English,11.000000,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515,English,10.500000,1982.0,7.9,34000,424.449459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Katsuhiro Ã”tomo,105.0,0.410388,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79,Japanese,2127.519898,2004.0,6.9,973,-2127.109510
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809
3005,Lajos Koltai,73.0,0.195888,Drama|Romance|War,Marcell Nagy,Fateless,5603,45,Hungarian,2500.000000,2005.0,7.1,607,-2499.804112
3859,Chan-wook Park,202.0,0.211667,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131,Korean,4200.000000,2005.0,7.7,4000,-4199.788333
2988,Joon-ho Bong,363.0,2.201412,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279,Korean,12215.500000,2006.0,7.0,7000,-12213.298588

In [25]:
#Top 10 movies that made more profit#
top10 = movies.sort_values(by='profit',ascending=False).head(10)

In [26]:
top10.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515,English,10.5,1982.0,7.9,34000,424.449459

In [27]:
#Dropping the duplicates#
movies.drop_duplicates(keep='first',inplace=True)

In [28]:
top10.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515,English,10.5,1982.0,7.9,34000,424.449459

In [29]:
#Again top10 movies made more profit#
top10 = movies.sort_values(by='profit',ascending=False).head(10)

In [30]:
top10.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515,English,10.5,1982.0,7.9,34000,424.449459

In [31]:
###IMDB TOP 250###
IMDb_Top_250=movies[movies['num_voted_users']>25000].sort_values(by='imdb_score',ascending=False).head(250)

In [32]:
IMDb_Top_250.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144,English,25.0,1994.0,9.3,108000,3.341469
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238,English,6.0,1972.0,9.2,43000,128.821952
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650,English,13.0,1974.0,9.0,14000,44.300000
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667,English,185.0,2008.0,9.0,37000,348.316061
4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780,Italian,1.2,1966.0,8.9,20000,4.900000

In [33]:
#Sorting it in descending order#
IMDb_Top_250['Rank']=IMDb_Top_250['imdb_score'].rank(method='first',ascending=False)

In [34]:
IMDb_Top_250.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144,English,25.0,1994.0,9.3,108000,3.341469,1.0
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238,English,6.0,1972.0,9.2,43000,128.821952,2.0
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650,English,13.0,1974.0,9.0,14000,44.300000,3.0
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667,English,185.0,2008.0,9.0,37000,348.316061,4.0
4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780,Italian,1.2,1966.0,8.9,20000,4.900000,5.0

In [35]:
#Top 250 movies in English Language#
IMDb_Top_250[IMDb_Top_250['language']!='English']

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780,Italian,1.200000,1966.0,8.9,20000,4.900000,5.0
4747,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596,Japanese,2.000000,1954.0,8.7,11000,-1.730939,17.0
4029,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200,749,Portuguese,3.300000,2002.0,8.7,28000,4.263397,20.0
2373,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902,Japanese,19.000000,2001.0,8.6,28000,-8.950114,23.0
4259,Florian Henckel von Donnersmarck,215.0,11.284657,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407,German,2.000000,2006.0,8.5,39000,9.284657,35.0
4921,Majid Majidi,46.0,0.925402,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130,Persian,0.180000,1997.0,8.5,0,0.745402,39.0
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809,47.0
2970,Wolfgang Petersen,96.0,11.433134,Adventure|Drama|Thriller|War,JÃ¼rgen Prochnow,Das Boot,168203,426,German,14.000000,1981.0,8.4,11000,-2.566866,49.0
4105,Chan-wook Park,305.0,2.181290,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809,Korean,3.000000,2003.0,8.4,43000,-0.818710,57.0
4659,Asghar Farhadi,354.0,7.098492,Drama|Mystery,Shahab Hosseini,A Separation,151812,264,Persian,0.500000,2011.0,8.4,48000,6.598492,58.0
1329,S.S. Rajamouli,44.0,6.498000,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410,Telugu,18.026148,2015.0,8.4,21000,-11.528148,59.0
1298,Jean-Pierre Jeunet,242.0,33.201661,Comedy|Romance,Mathieu Kassovitz,AmÃ©lie,534262,1314,French,77.000000,2001.0,8.4,39000,-43.798339,61.0
2734,Fritz Lang,260.0,0.026435,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413,German,6.000000,1927.0,8.3,12000,-5.973565,65.0
4033,Thomas Vinterberg,349.0,0.610968,Drama,Thomas Bo Larsen,The Hunt,170155,249,Danish,3.800000,2012.0,8.3,60000,-3.189032,73.0
2829,Oliver Hirschbiegel,192.0,5.501940,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564,German,13.500000,2004.0,8.3,14000,-7.998060,81.0
2551,Guillermo del Toro,406.0,37.623143,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083,Spanish,13.500000,2006.0,8.2,27000,24.123143,86.0
4000,Juan JosÃ© Campanella,262.0,20.167424,Drama|Mystery|Thriller,Ricardo DarÃ­n,The Secret in Their Eyes,131831,231,Spanish,2.000000,2009.0,8.2,33000,18.167424,97.0
3550,Denis Villeneuve,226.0,6.857096,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156,French,6.800000,2010.0,8.2,37000,0.057096,98.0
2047,Hayao Miyazaki,212.0,4.710455,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330,Japanese,24.000000,2004.0,8.2,13000,-19.289545,100.0
2830,Alejandro AmenÃ¡bar,157.0,2.086345,Biography|Drama|Romance,BelÃ©n Rueda,The Sea Inside,64556,140,Spanish,10.000000,2004.0,8.1,0,-7.913655,110.0
2914,Je-kyu Kang,86.0,1.110186,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224,Korean,12.800000,2004.0,8.1,0,-11.689814,119.0
4461,Thomas Vinterberg,98.0,1.647780,Drama,Ulrich Thomsen,The Celebration,65951,258,Danish,1.300000,1998.0,8.1,5000,0.347780,127.0
3553,JosÃ© Padilha,142.0,0.008060,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107,Portuguese,4.000000,2007.0,8.1,11000,-3.991940,143.0
3423,Katsuhiro Ã”tomo,150.0,0.439162,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430,Japanese,1100.000000,1988.0,8.1,0,-1099.560838,147.0
4267,Alejandro G. IÃ±Ã¡rritu,157.0,5.383834,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361,Spanish,2.000000,2000.0,8.1,11000,3.383834,152.0
3456,Vincent Paronnaud,242.0,4.443403,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194,158,French,7.300000,2007.0,8.0,14000,-2.856597,166.0
3344,Karan Johar,210.0,4.018695,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235,Hindi,12.000000,2010.0,8.0,27000,-7.981305,175.0
4144,Walter Salles,71.0,5.595428,Drama,Fernanda Montenegro,Central Station,28951,257,Portuguese,2.900000,1998.0,8.0,0,2.695428,177.0
4284,Ari Folman,231.0,2.283276,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107,156,Hebrew,1.500000,2008.0,8.0,0,0.783276,181.0
4897,Sergio Leone,122.0,3.500000,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566,235,Italian,0.200000,1964.0,8.0,0,3.300000,183.0
1171,Yimou Zhang,283.0,0.084961,Action|Adventure|History,Jet Li,Hero,149414,841,Mandarin,31.000000,2002.0,7.9,0,-30.915039,212.0
2863,Clint Eastwood,251.0,13.753931,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316,Japanese,19.000000,2006.0,7.9,5000,-5.246069,226.0
3264,Michael Haneke,447.0,0.225377,Drama|Romance,Isabelle Huppert,Amour,70382,190,French,8.900000,2012.0,7.9,33000,-8.674623,229.0
3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119,Hindi,7.000000,2004.0,7.9,2000,-4.078262,233.0
3677,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110,French,5.500000,2004.0,7.9,0,-1.870242,237.0
4415,FabiÃ¡n Bielinsky,94.0,1.221261,Crime|Drama|Thriller,Ricardo DarÃ­n,Nine Queens,38215,125,Spanish,1.500000,2000.0,7.9,0,-0.278739,243.0
4640,Cristian Mungiu,233.0,1.185783,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172,Romanian,0.590000,2007.0,7.9,14000,0.595783,244.0
2605,Ang Lee,287.0,128.067808,Action|Drama|Romance,Chen Chang,"Crouching Tiger, Hidden Dragon",217740,1641,Mandarin,15.000000,2000.0,7.9,0,113.067808,247.0

In [36]:
###BEST DIRECTORS###
top10director=movies.groupby('director_name').imdb_score.mean().sort_values(ascending=False).head(10)

In [37]:
top10director.head()

director_name
Charles Chaplin     8.6
Tony Kaye           8.6
Alfred Hitchcock    8.5
Ron Fricke          8.5
Damien Chazelle     8.5
Name: imdb_score, dtype: float64

In [38]:
###POPULAR GENRES###
TempGenre=movies.genres.str.split('|',expand=True).iloc[:,0:2]
TempGenre.columns=['genre_1','genre_2']
TempGenre.genre_2.fillna(TempGenre.genre_1,inplace=True)

In [39]:
TempGenre.head()

  genre_1    genre_2
0  Action  Adventure
1  Action  Adventure
2  Action  Adventure
3  Action   Thriller
5  Action  Adventure

In [42]:
###CRITIC FAVOURITE AND AUDIENCE FAVOURITE###
Meryl_Streep = movies[movies['actor_1_name']=='Meryl Streep']
Leo_Caprio = movies[movies['actor_1_name']=='Leonardo DiCaprio']
Brad_Pitt = movies[movies['actor_1_name']=='Brad Pitt']
combined=Meryl_Streep.append([Leo_Caprio,Brad_Pitt])

AttributeError: 'DataFrame' object has no attribute 'append'

:

In [ ]:
combined.groupby('actor_1_name')['num_critic_for_reviews','num_user_for_reviews'].mean()

In [ ]:
#CALCULATED DACADES#
movies['decade']=movies['title_year'].apply(lambda x: (x//10)*10).astype(np.int64)
movies['decade']=movies['decade'].astype(str)+'s'
movies=movies.sort_values(['decade'])

In [ ]:
#CREATED DATAFRAME BY DECADE#
df_by_decade=movies.groupby('decade')
df_by_decade['num_voted_users'].sum()
df_by_decade=pd.DataFrame(df_by_decade['num_voted_users'].sum())

In [ ]:
#plotted the bar graph for number of voted users vs decade#
df_by_decade.plot.bar(figsize=(15,8),width=0.8,hatch="//",edgecolor
='k')
plt.xlabel("Decade")
plt.ylabel("Voted Users")
plt.title("Voted users over Decades")
plt.yscale('log')
plt.show()

In [ ]:
#SAVING THE NEW DATASET#
movies.to_csv("cleaned_data_0.csv")